language: node_js
# because we need to package on osx
os: osx
node_js:
  - 10
sudo: false
before_deploy: npm i && npm run build
deploy:
  provider: releases
  api_key:
    secure: CVyYsRaccIp5VKvRsza7HHoIQVGRsnBE6wsUg+s0ZL4r4qoHLAr5/iH+HZw7RhHIFsHDhynbbDeOwk+mwNFrF+N5hJB1xLkRu8jkPyIp46EbdSVRFfYdr+80zKCD6GM1UNksmjxqIsuzvHmP4bGWyLryLkLXI6FqbxAsU3OTLQ5xIEI2Biy7ZZTz67uv1wSxNnWWsYgtxwZQTQwkc5HbM8UpP8a0eMtOEm4JUC+JEMBNwmm3RzqDgEWbHzaKME+sl+RiMT4J+yakdSV84DXSCASIoKI6MI7Y54a34/PC32WvxCh7k3WnM8qqhSc7O6lqcohdjHKaVtNzxgKbYnjpwipbQZ42yF7imssYFjILL36FhAnmv7IYcdHoCHq9i/h1fi7F7tIjlQnu3sTYGXBLVe3zCBGisjajb2kE91EMbh0Irg9OIQcu2gEKxxZ9np78HWpHFPnfK9sxb5g9wSvOBtK6zgL7B2Ycn0Zrruqb/7er5ScCMDQyj1No6a3G9dKGUBtzUz/mo1/c9Bznd1pQyecNXKBIPOboTO0P+nVKG2vkPQEsDgfP2xQocNiqELTnXDkEAGpVSw1w8crH/fmXx7Mdg8Ds8o8XxqmVurJW8VKffalcl6zRCUdUazm4ubDgIr7SD4jChYjI53BAU9ZGkb4cJcrBHy0xH5rG9j8LPbA=
  file: package/PomoDisturb.dmg
  skip_cleanup: true
  overwrite_files: true
  on:
    repo: NickTomlin/pomo-disturb
    tags: true
